name: Prueba de mensaje github actions

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Mostrar mensaje
      run: |
        echo "Hola"
        echo "Fecha y hora:"
        date
        echo "Versi√≥n de Java:"
        java -version || echo "Java no instalado"        